# Generated by Django 3.1 on 2020-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_group_max_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_group_size',
            field=models.IntegerField(default=5),
        ),
    ]
