# Generated by Django 3.1 on 2020-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_auto_20200813_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.CharField(default='uditg', max_length=50),
        ),
    ]
