# Generated by Django 3.1 on 2020-09-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
