# Generated by Django 3.1 on 2020-09-08 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_message_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
