# Generated by Django 3.1 on 2020-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchatapp', '0002_auto_20200908_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
